name: open_luz
description: "Detailed information on electricity prices in Spain (PVPC) for efficient electricity consumption management."
publish_to: 'none'
version: 2.0.0+2

environment:
  sdk: ^3.9.2

dependencies:
  archive: ^4.0.7
  csv: ^6.0.0
  dio: ^5.9.0
  envied: ^1.2.1
  envied_generator: ^1.1.1
  file_picker: ^10.3.3
  fl_chart: ^1.1.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.1
  geekyants_flutter_gauges: ^1.0.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  http: ^1.5.0
  intl: ^0.20.2
  path: ^1.9.1
  path_provider: ^2.1.5
  printing: ^5.14.2
  screenshot: ^3.0.0
  share_plus: ^12.0.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  
flutter_launcher_icons:
  android: true
  ios: false
  image_path_android: assets/icon/pvpc_icon.png
  image_path_ios: assets/icon/pvpc_ios.png
  adaptive_icon_background: "#1565c0"
  #adaptive_icon_background: assets/icon/ic_background.png
  adaptive_icon_foreground: assets/icon/ic_foreground.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/eprel/
    - assets/images/eprel/categorias/
    - assets/images/eprel/etiquetas/
    - assets/files/
    - assets/google_fonts/
  fonts:
    - family: CairoPlay
      fonts:
        - asset: assets/google_fonts/CairoPlay-ExtraLight.ttf
          weight: 200
        - asset: assets/google_fonts/CairoPlay-Light.ttf
          weight: 300
        - asset: assets/google_fonts/CairoPlay-Regular.ttf
          weight: 400
        - asset: assets/google_fonts/CairoPlay-Medium.ttf
          weight: 500
        - asset: assets/google_fonts/CairoPlay-SemiBold.ttf
          weight: 600
        - asset: assets/google_fonts/CairoPlay-Bold.ttf
          weight: 700
        - asset: assets/google_fonts/CairoPlay-ExtraBold.ttf
          weight: 800
        - asset: assets/google_fonts/CairoPlay-Black.ttf
          weight: 900
